Denote

diff --git a/themes/after-dark/bin/install b/themes/after-dark/bin/install
--- a/themes/after-dark/bin/install
+++ b/themes/after-dark/bin/install
@@ -1,6 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env -S sh -euo pipefail
+
 #
-# Copyright (C) 2019  VHS <vhsdev@tutanota.com>
+# Copyright (C) 2019, 2023  VHS <vhsdev@tutanota.com>
 #
 # This file is part of After Dark.
 #
@@ -18,7 +19,12 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 
-set -eu
+vers() { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
+parse_hugo_vers() {
+   hugovers=$(hugo version | sed 's/-.*//')
+   hugovers="${hugovers#"${hugovers%%[0-9]*}"}"
+   HUGO_VERSION=${hugovers}
+}
 
 validate_hugo() {
    # Exit with error if hugo is not installed
@@ -28,9 +34,9 @@ validate_hugo() {
    fi
 
    # Exit with error if not minimum required hugo version
-   re="v(0\d*\.([5-9][1-9]|[6-9])|[1-9]).*"
-   if ! hugo version | grep -qE "$re"; then
-      echo "Error: After Dark requires Hugo version 0.51 or greater" >&2
+   parse_hugo_vers
+   if [ "$(vers "$HUGO_VERSION")" -lt "$(vers "0.51")" ]; then
+      echo "Error: After Dark requires Hugo version 0.51 or greater"
       exit 1
    fi
 }
@@ -49,10 +55,14 @@ confirm_intent() {
    done
 }
 
+set_default_site_name() {
+   SITE_NAME="Flying Toasters"
+}
+
 prompt_site_name() {
    printf "Please enter a name for your site: "
    read -r response </dev/tty
-   SITE_NAME=$(echo "$response" | tr -cd '[:alnum:] [:space:]' | tr -s '[:space:]')
+   SITE_NAME="$(echo "$response" | tr -cd '[:alnum:] [:space:]' | tr -s '[:space:]')"
    while true; do
       printf "You entered %s. Is that correct? (y/n) " "\"$SITE_NAME\""
       read -r yn </dev/tty
@@ -73,8 +83,12 @@ format_dir_name() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]._-'
 }
 
+set_default_install_dir() {
+   SITE_DIR="$(format_dir_name "$SITE_NAME")"
+}
+
 prompt_install_dir() {
-   default_dir=$(format_dir_name "$SITE_NAME")
+   default_dir="$(format_dir_name "$SITE_NAME")"
    printf "Choose an installation directory name (%s): " "$default_dir"
    read -r response </dev/tty
    if [ "$response" = "" ]; then
@@ -120,10 +134,10 @@ create_site() {
 
 download_theme() {
    echo "Downloading the latest version of After Dark ..."
-   LATEST_META=$(wget -qO - https://registry.npmjs.org/after-dark/latest)
+   LATEST_META=$(wget -qO- https://registry.npmjs.org/after-dark/latest)
    vers=$(echo "$LATEST_META" | grep -oE "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
    mkdir -p themes/after-dark
-   wget -qO - https://registry.npmjs.org/after-dark/-/after-dark-"$vers".tgz | tar --strip-components=1 -xz -C themes/after-dark
+   wget -qO- https://registry.npmjs.org/after-dark/-/after-dark-"$vers".tgz | tar --strip-components=1 -xz -C themes/after-dark
    echo "Version $vers downloaded to $SITE_DIR/themes/after-dark"
 }
 
@@ -133,21 +147,24 @@ download_module() {
       exit 1
    }
    echo "Downloading $1 module for After Dark ..."
-   meta=$(wget -qO - https://registry.npmjs.org/"$1"/latest)
+   meta=$(wget -qO- https://registry.npmjs.org/"$1"/latest)
    vers=$(echo "$meta" | grep -oE "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
    mkdir -p themes/"$1"
-   wget -qO - https://registry.npmjs.org/"$1"/-/"$1"-"$vers".tgz | tar --strip-components=1 -xz -C themes/"$1"
+   wget -qO- https://registry.npmjs.org/"$1"/-/"$1"-"$vers".tgz | tar --strip-components=1 -xz -C themes/"$1"
    echo "Version $vers downloaded to $SITE_DIR/themes/$1"
 }
 
 configure_theme() {
    echo "Configuring basic After Dark theme settings ..."
-   tee "config.toml" >/dev/null <<TOML
+   configfile=config.toml
+   parse_hugo_vers
+   [ "$(vers "$HUGO_VERSION")" -ge "$(vers "0.112")" ] && configfile=hugo.toml
+   tee "${configfile}" >/dev/null <<TOML
 baseurl = "https://domain.example" # Controls base URL sitewide
 languageCode = "en-US" # Controls site language
 title = "$SITE_NAME" # Homepage title and page title suffix
 paginate = 11 # Number of posts to show before paginating
-copyright = "Copyright &copy; Copyright Owner. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC-BY-ND-4.0</a>." # Optional, remove to suppress copyright notices
+copyright = "Copyright &copy; Copyright Owner. Licensed under <a target=\"_blank\" rel=\"external license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC BY-ND 4.0</a>." # Optional, remove to suppress copyright notices
 
 # Controls default theme and theme components
 theme = [
@@ -199,6 +216,11 @@ create_welcome_post() {
    hugo new post/welcome.md 1>/dev/null
 }
 
+serve_site() {
+   echo "Starting site server ..."
+   hugo serve --buildDrafts --navigateToChanged --port 1313 1>/dev/null &
+}
+
 generate_help_docs() {
    echo "Generating help documentation ..."
    THEME_PATH=themes/after-dark
@@ -208,12 +230,24 @@ generate_help_docs() {
    hugo new validate.md --kind validate 1>/dev/null
 }
 
+serve_help() {
+   echo "Starting help server ..."
+   hugo serve --disableLiveReload --port 1414 1>/dev/null &
+}
+
 echo "Welcome to the After Dark quick installer. Press CTRL-C at any time to abort."
 
-confirm_intent
+if [ -n "${AFTRDRK_INTERACTIVE_INSTALL-}" ]; then
+   confirm_intent
+fi
 validate_hugo
-prompt_site_name
-prompt_install_dir
+if [ -n "${AFTRDRK_INTERACTIVE_INSTALL-}" ]; then
+   prompt_site_name
+   prompt_install_dir
+else
+   set_default_site_name
+   set_default_install_dir
+fi
 create_site_dir
 create_site
 download_theme
@@ -221,12 +255,17 @@ update_archetypes
 download_module "fractal-forest"
 configure_theme
 create_welcome_post
+serve_site
 generate_help_docs
+serve_help
 
-YELLOW='\033[0;33m'
-NC='\033[0m'
+lime_yellow=$(tput setaf 190)
+normal=$(tput sgr0)
 
-echo "${YELLOW}Installation successful!${NC}"
+printf '%sInstallation successful!%s\n' "${lime_yellow}" "${normal}"
 echo "Site created in $SITE_DIR_ABS"
-echo "Serve your site with \"hugo serve --buildDrafts --navigateToChanged\""
+echo "Site server started at http://localhost:1313/"
+echo "To stop it run \"kill \$(ps aux | awk '/[h]ugo.*1313/ {print \$2}')\"."
+echo "Help server started at http://localhost:1414/"
+echo "To stop and restart it run \"./themes/after-dark/bin/help\"."
 echo "Thank you for choosing After Dark."
